"""empty message

Revision ID: cdc03e2c303b
Revises: 
Create Date: 2023-09-25 02:17:18.163199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cdc03e2c303b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('genres', postgresql.ARRAY(
        sa.Enum(
            'Drama', 'Mystery', 'War', 'Short', 'Documentary', 'Action', 'Reality',
            'Romance', 'Comedy', 'Music', 'Scifi', 'Fantasy', 'Adventure', 'Horror',
            'Biography', 'Family', 'Thriller', 'Crime', 'Western', 'Adult', 'History',
            'Sport', 'Animation', 'Musical', 'FilmNoir', 'News', 'TalkShow', 'GameShow',
            name='genre', native_enum=False)
    ), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('runtime', sa.Integer(), nullable=True),
    sa.Column('imdb_url', sa.String(length=512), nullable=False),
    sa.Column('time_updated',
              sa.DateTime(),
              server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
              nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_movie')),
    sa.UniqueConstraint('imdb_url', name=op.f('uq_movie_imdb_url'))
    )
    op.create_index(op.f('ix_movie_rating'), 'movie', ['rating'], unique=False)
    op.create_index(op.f('ix_movie_title'), 'movie', ['title'], unique=False)
    op.create_index(op.f('ix_movie_year'), 'movie', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movie_year'), table_name='movie')
    op.drop_index(op.f('ix_movie_title'), table_name='movie')
    op.drop_index(op.f('ix_movie_rating'), table_name='movie')
    op.drop_table('movie')
    # ### end Alembic commands ###
